### ISSUE TITLE
UTF-8 with BOM and UTF-8

### ISSUE THREAD

**Issue by TemaSM** [amrali-eg/EncodingChecker#1]
Selecting `utf-8` in `Convert to` select list, should mean that files will be converted to `utf-8` without BOM.
Now, my files converted to `utf-8` and that's really fine, thanks! But, also my files now have `BOM` within UTF-8.
So, `EncodingChecker` should have two different converter options: `utf-8` and `utf-8 bom`

**Comment by amrali-eg** [comment]
I will try to fix it once I have the time. Thanks
