### ISSUE TITLE
KOI8-R is incorrectly recognized as 1251

### ISSUE THREAD

**Issue by sergeevabc** [amrali-eg/EncodingChecker#6]
Source: [koi8-r.zip](https://github.com/amrali-eg/EncodingChecker/files/6393327/koi8-r.zip)

**Comment by amrali-eg** [comment]
It is correctly identified as in the the screenshot below:
![Capture](https://user-images.githubusercontent.com/32075105/116824051-c1344280-ab90-11eb-9451-050607b2fec8.PNG)
