### ISSUE TITLE
Can't start the encoding checker even though dll and exe are in same directory 

### ISSUE THREAD

**Issue by LulaSvob** [amrali-eg/EncodingChecker#8]
Here is what error I get when I try to start the exe from the same directory as the dll on Windows 10 latest update:

![image](https://user-images.githubusercontent.com/32610546/130970048-b98dbf48-6505-4905-a79a-93d07ebf55e2.png)

**Comment by Ob1bob** [comment]
I also get this error message.

**Comment by amrali-eg** [comment]
Dll code is now inside exe
