### ISSUE TITLE
Support detection of utf8bom

### ISSUE THREAD

**Issue by geocine** [amrali-eg/EncodingChecker#9]
Right now I can only see utf8 (at least on the interface), I think utf8 (w or w/o BOM are grouped together). I have some projects where I need to make sure that utf8bom is used for all the files

**Comment by Norlandz** [comment]
I think utf8 is shown as ascii , utf8bom is shown as utf8. 
The results are compared by Notepad++ vs EncodingChecker.
I could be mistaken though.

**Comment by amrali-eg** [comment]
I Implemented BOM detection capability for view, validate and convert in the last update.
